---
title: "Stats Model"
output: html_notebook
---

```{r}
library(tidyverse)
outcomes <- readRDS(file = '../data/outcomes.rds')
```

```{r}
outcomes <- outcomes %>% 
  mutate(elo_diff = home_elo - away_elo, goal_diff = home_score - away_score, audience = if_else(Attendance == 0, 1, 0))

outcomes_20_21 <- outcomes %>% 
  filter(date > '2020-09-01', date < '2021-06-30')
```

```{r}
every_year_goal_diff <- lm(goal_diff ~ elo_diff, data = outcomes)

summary(every_year_goal_diff)
```

```{r}
every_year_home_percent <- glm(home_win ~ elo_diff, data = outcomes, family = 'binomial')

summary(every_year_home_percent)
```
```{r}
ever_year_home_percent_audience <- glm(home_win ~ elo_diff + audience, data = outcomes, family = 'binomial')

summary(ever_year_home_percent_audience)
```

```{r}
year_20_21_goal_diff <- lm(goal_diff ~ elo_diff, data = outcomes_20_21)

summary(year_20_21_goal_diff)
```

```{r}
year_20_21_home_percent <- glm(home_win ~ elo_diff, data = outcomes_20_21, family = 'binomial')

summary(year_20_21_home_percent)
```

```{r}
year_20_21_home_percent_audience <- glm(home_win ~ elo_diff + audience, data = outcomes_20_21, family = 'binomial')

summary(year_20_21_home_percent_audience)
```

